---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[devops-challenge::default]
    driver:
      vm_hostname: hostname
      network:
        - ["private_network", {ip: "192.168.237.17"}]
